### ISSUE TITLE
.editorconfig location on windows

### ISSUE THREAD

**Issue by ksmith97** [maksimr/vim-jsbeautify#101]
I was really stumped why it would not load my .editorconfig and I eventually came to the conclusion that it does not properly recognize that in gvim on windows the .vim folder is actually vimfiles instead. By moving my config to the root of my home it worked but I spent quite a bit of time and it was frustrating!

**Comment by maksimr** [comment]
@ksmith97 Thanks for feedback!
It will be cool if you resolve this issue for Windows and make pull request

**Comment by x11x** [comment]
Hi, I've made a pull request to fix this.
Cheers

**Comment by maksimr** [comment]
@x11x Awesome! Thanks a lot
