### ISSUE TITLE
Better support for ES6

### ISSUE THREAD

**Issue by alexbooker** [maksimr/vim-jsbeautify#103]
Consider the following JS code:

```javascript
export default function() {
}
```

Upon running _vim-jsbeautify_ the code is transformed into...

```javascript
export 
default function() {
}
```

...Which is clearly erroneous.

When I run the same code through [the online beautifer](http://jsbeautifier.org/) the code is formatted as I would expect. I _suspect_ the _jsbeautify_ dependency needs updating?

**Comment by maksimr** [comment]
@alexbooker yup, but you can use [custom version of js-beautify](https://github.com/maksimr/vim-jsbeautify#examples)

**Comment by mydearxym** [comment]
also turn my react code to wrong format

```js
import React from 'react'

export default class Forbidden extends React.Component {
  render () {
    return (
      <div className="container">
        <div>
          <div>forbidden</div>
        </div>
        <div>
          <div>notAuthorized</div>
        </div>
      </div>
    )
  }
}
```

```js
import React from 'react'

export
default class Forbidden extends React.Component {
    render() {
        return ( < div className = "container" >
            < div >
            < div > forbidden < /div>
        </div >
            < div >
            < div > notAuthorized < /div>
        </div >
            < /div>
    )
  }
}

```

**Comment by maksimr** [comment]
@mydearxym can you put your .editorconfig

**Comment by mydearxym** [comment]
@maksimr   it's basically the same as README.md shows : 

```js
 ; .editorconfig

  root = true

  [**.js]
  indent_style = space
  indent_size = 4
  e4x = true

  [**.jsx]
  e4x = true
  indent_style = space
  indent_size = 4

  [**.css]
  indent_style = space
  indent_size = 4

  [**.html]
  indent_style = space
  indent_size = 4
  max_char = 78
  brace_style = expand

```

**Comment by maksimr** [comment]
@mydearxym thanks. Are you use custom version of js-beautify?

**Comment by mydearxym** [comment]
@maksimr   Nope, just the common version .

**Comment by maksimr** [comment]
@mydearxym try download latest version of js-beautify and set it in .editorconfig

**Comment by maksimr** [comment]
@mydearxym for jsx you should call JsxBeautify

**Comment by mydearxym** [comment]
@maksimr   thanks !

**Comment by zeroliu** [comment]
I'm experiencing the same issue.

`export default foo` is turned into
```
export
default foo
```

I am also unable to load .editorconfig so that I am using inline configs.
```
let g:config_Beautifier = {}
let g:config_Beautifier['js'] = {}
let g:config_Beautifier['js'].indent_size = '2'
```

**Comment by zeroliu** [comment]
ah, manually checkout the latest version of js-beautify works. The submodule used in vim-jsbeautify is out of date.

cd ~/.vim/bundle/vim-jsbeautify/plugin/lib && git checkout master

**Comment by maksimr** [comment]
Related issue https://github.com/maksimr/vim-jsbeautify/pull/104
