### ISSUE TITLE
doesn't support closest .editorconfig file?

### ISSUE THREAD

**Issue by jayceekay** [maksimr/vim-jsbeautify#105]
i noticed this part of the readme: `This file can be located either in the user home directory ~/.editorconfig, or in inside the vim configuration directory ~/.vim/.editorconfig.`, so maybe this is a silly question, but does this plugin support a per project `.editorconfig`?

**Comment by maksimr** [comment]
@jayceekay yup

**Comment by jayceekay** [comment]
okay, cool. i figured it did but didn't notice that mentioned in the readme.

anyways, can you help me figure out what i'm doing wrong here? i've copied the project `.editorconfig` to  `~/.editorconfig`and `~/.vim/.editorconfig` with no results as it's not respecting the `indent_size = 2` setting.

here's the project editorconfig:
```
justink@Justins-MacBook-Pro:~/dev/magicplaylist (master) $ cat .editorconfig
root = true

[**]
indent_style = space
indent_size = 2
end_of_line = LF
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[**.md]
trim_trailing_whitespace = false
```

copied ones as a sanity check:
```
justink@Justins-MacBook-Pro:~/dev/magicplaylist (master) $ ls ~/.editorconfig && ls ~/.vim/.editorconfig
/Users/justink/.editorconfig
/Users/justink/.vim/.editorconfig
```

gif of me getting no respect as it still wants to indent to 4 spaces ;(

![norespect](https://cloud.githubusercontent.com/assets/1119866/10869305/3caf2a22-8079-11e5-9e22-5f9ea05b8e9e.gif)

**Comment by maksimr** [comment]
@jayceekay you should write [**.js] instead [**] because **global** editorconfig [we parse our plugin](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L97-L162) not by vim-editorconfig :(
A better solution, is welcome

**Comment by jayceekay** [comment]
@maksimr i'd like to contribute to this, do you guys have a chat or some way of communicating that's not github issues?

**Comment by maksimr** [comment]
@jayceekay no
