### ISSUE TITLE
Some code style options do not take effect

### ISSUE THREAD

**Issue by lookforit** [maksimr/vim-jsbeautify#107]
Hi
I installed this plugin ,and set `.editorconfig` like:
[**.js]
indent_style = space
indent_size = 4
indent_brace_style= Allman
curly_bracket_next_line=true
spaces_around_operators= true
spaces_around_brackets= inside

Then ,open a js file, and `:call JsBeautify()`.
I noticed that **some changes happen ,but some code style fail to appear:**
```js
if (!filename) {
    throw Error("Please specify a file");
}
```
As you see:

*  The brace style I want is **Allman**,but the reality is **K&R**
*  No spaces inserted in brackets

However, the `echo b:config_Beautify` output is normal:

{'jsx': {'indent_char': ' ', 'e4x': 'true', 'indent_style': 'space', 'indent_size': '4'}, 'js': {'spaces_around_operators': 'true', 'inde
nt_char': ' ', 'spaces_around_brackets': 'inside', 'indent_style': 'space', 'indent_size': '4', 'indent_brace_style': 'Allman', 'curly_br
acket_next_line': 'true'}, 'json': {'indent_char': ' ', 'indent_style': 'space', 'indent_size': '4'}, 'html': {'indent_char': ' ', 'brace
_style': 'expand', 'indent_style': 'space', 'indent_size': '4', 'max_char': '78'}, 'css': {'indent_char': ' ', 'indent_style': 'space', '
indent_size': '4'}}

Any help will be appropriated.

**Comment by maksimr** [comment]
@lookforit try install [js-beautifier](http://jsbeautifier.org/) and run it on your code. Passing options which you define in .editorconfig.

Seems problem not in vim plugin

**Comment by lookforit** [comment]
Yes, I use the `Editor Config` property :
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

That's the point!

The right way of setting the options is using  js-beautify's option,just as you listed above.

I think the config file's name: `.editorconfig` traps me :smile:

**Comment by maksimr** [comment]
@lookforit yup. We can add mapping on common options from editorconfig to js-beatufiy

https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L169-L187

**Comment by nivv** [comment]
@lookforit hey man, can I have a look at your `.editorconfig`? I can't seem to get the `brace_style`-option to work.

**Comment by maksimr** [comment]
@nivv https://github.com/maksimr/dotfiles/blob/master/export/_editorconfig.symlink
