### ISSUE TITLE
Odd formatting with JSX

### ISSUE THREAD

**Issue by dannycroft** [maksimr/vim-jsbeautify#110]
Problem:

When I call JsBeautify() I get superfluous spacing around the chevrons within the markup: 

![jsx-indent](https://cloud.githubusercontent.com/assets/87240/12328119/3b96044e-bada-11e5-9885-c57134c21c9d.gif)

A copy of my .vimrc can be seen [here](https://gist.github.com/dannycroft/d711a92831ded0903e28)

I spent the last hour bisecting my vim plugins to make sure it wasn't one of the others causing this, but to no avail. If anyone can spot my downfall that would be greatly appreciated. My .editorconfig can be seen in the gif above, but I'll add it below also: 

```
; .editorconfig

root = true

[**.js]
path=~/.vim/bundle/js-beautify/js/lib/beautify.js
bin = node
indent_style = space
indent_size = 2

[**.json]
indent_style = space
indent_size = 2

[**.jsx]
e2x = true
indent_style = space
indent_size = 2

[**.css]
path=~/.vim/bundle/js-beautify/js/lib/beautify-css.js
indent_style = space
indent_size = 2

[**.html]
;vim:path=~/.vim/bundle/js-beautify/js/lib/beautify-html.js
indent_style = space
indent_size = 2
max_char = 78
brace_style = expand
```

**Comment by maksimr** [comment]
Hi @dannycroft 
Try `:call JsxBeautify()<cr>` instead `jsBeautify`

**Comment by maksimr** [comment]
@dannycroft `call JsxBeautify()` fixed problem?

**Comment by dannycroft** [comment]
Cheers @maksimr. I did try both JsxBeautify() and JsBeautify(). I should have used the former in the gif example, my bad. Ultimately I ran out of time and had to find a different solution to formatting JSX files. Thank you for the help though. I suspect it was one of my other plugins, but couldn't see which one.

If you need any details for any future issues let me know.
