### ISSUE TITLE
Add ES7, ES6 support

### ISSUE THREAD

**Issue by ifokeev** [maksimr/vim-jsbeautify#121]
I updated js-beautify to 1.6.3 and now it works fine.
Please, approve the PR: https://github.com/maksimr/vim-jsbeautify/pull/120

**Comment by ifokeev** [comment]
Also, if you are formatting JSX files, use 
```:call JsxBeautify()```

**Comment by maksimr** [comment]
@ifokeev thanks for PR. Done
