### ISSUE TITLE
Doesn't work with vim-Plugged

### ISSUE THREAD

**Issue by nerdpad** [maksimr/vim-jsbeautify#122]
Hi,

I am trying to install this with vim Plugged, and it isn't working.

`:PlugStatus` shows the plugin is loaded, but `:JsBeautify` is not a valid command. I guess this is because the internal folder structure of this plugin.

Any clue how to get this working in NeoVim + vim-plugged?

Thanks,
Zuhaib

**Comment by maksimr** [comment]
Thanks for response, 
I don't use plugged so I can't help you if someone know how fix this problem *welcome*

**Comment by maksimr** [comment]
@NerdPad you can look to section about installing without any plugin manager https://github.com/maksimr/vim-jsbeautify#installing-without-plugin-manager maybe it helps you
