### ISSUE TITLE
Sass calc()

### ISSUE THREAD

**Issue by dantveita** [maksimr/vim-jsbeautify#125]
CSSBeautify messes up Sass calc-functions for me, but not sure if theres something wrong on my end — so this is a humble request. 

Example:

```
left: calc(-50vw + 50%);  // becomes... :  
left: calc(-50vw+ 50%);  // ...after calling CSSBeautify(), which obviously gives an error
```

**Comment by maksimr** [comment]
@dantveita thanks!

But I think it's issue of [js-beautify](https://github.com/beautify-web/js-beautify) not vim plugin.
