### ISSUE TITLE
How to get Airbnb's JavaScript style guide working with jsbeautify?

### ISSUE THREAD

**Issue by traidesar** [maksimr/vim-jsbeautify#127]
I have .eslintrc file and .editorconfig file, how should I set it?

**Comment by maksimr** [comment]
This plugin operates only with .editorconfig.
So all formatting stuff you should place in .editorfonfig.

Available options you can find in [js-beautify](https://github.com/beautify-web/js-beautify)

For example:

```.editorconfig
[**.js]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
```
