### ISSUE TITLE
Strange Formatting when JavaScript embedded in script tag in HTML

### ISSUE THREAD

**Issue by Asheq** [maksimr/vim-jsbeautify#130]
If I call HtmlBeautify() on the following (already well-formatted code):
![image](https://cloud.githubusercontent.com/assets/4657140/20853555/8d3b90be-b8a1-11e6-9f41-e7b1e75e58f1.png)

... I get the following: (notice the strange position of the brace)
![image](https://cloud.githubusercontent.com/assets/4657140/20853535/5fad3e68-b8a1-11e6-87b4-df469bfd0e30.png)

http://jsbeautifier.org/ does not do this strange formatting.

Am I doing something wrong?

Thanks for the help!

## Environment Info
**VIM**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2016 09:59:10)
MS-Windows 64-bit GUI version
Included patches: 1-3

**Node**
Node v6.7.0

**Command-line js-beatify**
v1.6.4

**Comment by maksimr** [comment]
@Asheq you can play with settings for js-beautify, I think problem in settings

Thanks

**Comment by Asheq** [comment]
Thanks for responding... The formatting is correct when I run js-beautify from the command-line. Either of the commands below work:

> html-beautify test.html

> js-beautify test.html --type html

which leads me to believe that it's not js-beautify itself that is causing the formatting issue.

**Comment by maksimr** [comment]
@Asheq [here](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/.editorconfig#L20-L23) default settings for html

**Comment by Asheq** [comment]
I think I narrowed down the solution. In [.editorconfig](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/.editorconfig) in the repo, line 21 needs a space after the leading `;`

This
> ;vim:max_char=78:brace_style=expand

needs to read

> ; vim:max_char=78:brace_style=expand

I have no idea what that line does, but adding the space solves the problem. It's just a comment right? May be the comment format requires a space. Do you have any idea about this?

Thanks

**Comment by maksimr** [comment]
@Asheq 

>  It's just a comment right? 

It is special comment, where you can define properties.
It will be nice if you create PR with fix

Thanks!
