### ISSUE TITLE
How to disable --extra_liners option?

### ISSUE THREAD

**Issue by afdallah** [maksimr/vim-jsbeautify#136]
According to the js-beautify help [documentation](https://www.npmjs.com/package/js-beautify#setting-inheritance-and-language-specific-overrides), there is an option named `--extra_liners` that will create an extra line before html, head, and body tags. That option is set to true by default, how to disable them? Thanks for the help!

![Gif](https://media.giphy.com/media/3og0IDrJMaDTvpIcdq/giphy.gif)

**Comment by maksimr** [comment]
Try set in your .editorconfig


```
[**.html]
extra_liners=false
```

Thanks

**Comment by afdallah** [comment]
Hi @maksimr I have tried your suggestion, but it seems like it didn't work. 

i added `extra_liners=false` to my .editorconfig located in home directory `~/.editorconfig` and in the project directory.

![Gif](https://media.giphy.com/media/xUA7aVuwFGa8Qaz97y/giphy.gif)

**Comment by maksimr** [comment]
@afdallah I have looked at the js-beautify code and I see that extra_liners can accept array and string so you can write this:

```
extra_liners = ""
```

or

```
extra_liners = []
```

**Comment by afdallah** [comment]
@maksimr It works perfectly. Sorry for my stupid question. 
Thanks for the help!

**Comment by maksimr** [comment]
@afdallah no problem :)

**Comment by Migacz85** [comment]
How the working line should exactly look like ?
