### ISSUE TITLE
The listchars setting is invalid after using JsBeautify

### ISSUE THREAD

**Issue by asins** [maksimr/vim-jsbeautify#137]
In my vimrc file, the listchars setting is used to display the indentation, but the effect of the listchars setting is invalid after the JsBeautify() is executed, and you need to reopen the file to display the effect of the listchars setting.

### My vimrc setting

```vim
" listchars setting
set listchars=tab:\|·,trail:·,extends:❯,precedes:❮,nbsp:×

" jsbeautify setting
Plug 'maksimr/vim-jsbeautify', { 'for': [ 'html', 'xml', 'javascript', 'css', 'less', 'scss'] }

autocmd BufNewFile,BufRead *.less,*.scss setlocal filetype=css
autocmd FileType css noremap <buffer> <silent> <Leader>ff :call CSSBeautify()<cr>
autocmd FileType javascript noremap <buffer> <silent> <Leader>ff :call JsBeautify()<cr>
autocmd FileType json noremap <buffer> <silent> <Leader>ff :call JsonBeautify()<cr>
autocmd FileType jsx noremap <buffer> <silent> <Leader>ff :call JsxBeautify()<cr>
autocmd FileType html noremap <buffer> <silent> <Leader>ff :call HtmlBeautify()<cr>
```

### Original file status
![image](https://user-images.githubusercontent.com/898354/27443058-908afd16-57a4-11e7-91e0-021f4275a9d2.png)

### Press the shortcut key (<Leader>ff) to execute JsBeautify()

![image](https://user-images.githubusercontent.com/898354/27443341-52f9daca-57a5-11e7-900e-1c49d594dcf8.png)

I hope I can keep the settings of listchars after JsBeautify. How do I need to solve this problem?

**Comment by maksimr** [comment]
@asins 

You can set `indent_style` in the .editorconfig

```
[**.js]
indent_style = tab
```

**Comment by asins** [comment]
But I want to use spaces as indented characters, which is our standard. 

There is not indented JsBeautify, check the listchars document that is based on Tab, so the solution is to open automatically when the 4 space replacement for Tab, when you close the file and then automatically replace Tab 4 spaces, a toss.

Now I'm using the `vim-indent-guides` plugin to solve my problem, but I prefer the original configuration to the effect.
![image](https://user-images.githubusercontent.com/898354/30142971-07bea106-93b6-11e7-886d-8ce50ffae7ef.png)

**Comment by maksimr** [comment]
@asins Sorry, I don't understand what you want and why this is vim-jsbeautify's issue because now js-beautify take your document with `tab`'s  and replace all `tab`'s on `space`'s and this is a right behavior because 

> I want to use spaces as indented characters, which is our standard.

and you don't see '.'(dots) because now there are `space`'s and in your `listchars` configuration no setting for `space` so You could add something like this:

```
:set listchars=space:X
```

or

```
autocmd BufWinEnter * setl conceallevel=2 concealcursor=nv
autocmd BufWinEnter * syn match LeadingSpace /\(^ *\)\@<= / containedin=ALL conceal cchar=·
```
https://www.reddit.com/r/vim/comments/5fxsfy/show_leading_spaces/

to highlight spaces.


Thanks
