### ISSUE TITLE
Why is my react native project it crooked?

### ISSUE THREAD

**Issue by gHashTag** [maksimr/vim-jsbeautify#138]
simple.js
![2017-09-07 22 38 15](https://user-images.githubusercontent.com/6774813/30181827-4a2a3b1a-941d-11e7-85cf-1d3261545018.png)

.vimrc
```
Plug 'maksimr/vim-jsbeautify'
let g:editorconfig_Beautifier = '~/.editorconfig'
map <Leader>f :call JsBeautify()<cr>
autocmd FileType javascript vnoremap <buffer> <Leader>f :call RangeJsBeautify()<cr>
autocmd FileType json vnoremap <buffer> <Leader>f :call RangeJsonBeautify()<cr>
autocmd FileType jsx vnoremap <buffer> <Leader>f :call RangeJsxBeautify()<cr>
autocmd FileType html vnoremap <buffer> <Leader>f :call RangeHtmlBeautify()<cr>
autocmd FileType css vnoremap <buffer> <Leader>f :call RangeCSSBeautify()<cr>
```
.editorconfig
```
root = true

[**.js]
indent_style = space
indent_size = 2

[**.json]
indent_style = space
indent_size = 2

[**.jsx]
e2x = true
indent_style = space
indent_size = 2

[**.css]
indent_style = space
indent_size = 2

[**.html]
indent_style = space
indent_size = 2
max_char = 78
brace_style = expand

```

**Comment by maksimr** [comment]
First of all you should rename simple.js to simple.**jsx**
also you should call JsxBeautify() for jsx files

```
    autocmd BufEnter *.jsx nnoremap <buffer>  <leader>f :call JsxBeautify()<cr>
```

Thanks

**Comment by gHashTag** [comment]
same
![bug mov](https://user-images.githubusercontent.com/6774813/30215469-bad11b68-94b8-11e7-8953-dc2361dfd30d.gif)

**Comment by maksimr** [comment]
Hm....

I have tested and all work for me.
Could post here the result of `:echo b:config_Beautifier` command.
Maybe the problem in the version of js-beautify. Do you use a custom version of js-beautify?

Thanks
![js-beautify-jsx](https://user-images.githubusercontent.com/616193/30216776-c0d6d378-94bc-11e7-9267-a38fe4cb04d8.gif)

**Comment by gHashTag** [comment]
`{'jsx': {'indent_char': ' ', 'indent_style': 'space', 'indent_size': '2', 'e2x': 'true'}, 'js': {'indent_char': ' ', 'indent_style': 'space', 'indent_size': '2'}, 'json': {'indent_c
har': ' ', 'indent_style': 'space', 'indent_size': '2'}, 'html': {'indent_char': ' ', 'brace_style': 'expand', 'indent_style': 'space', 'indent_size': '2', 'max_char': '78'}, 'css':
 {'indent_char': ' ', 'indent_style': 'space', 'indent_size': '2'}}`

**Comment by gHashTag** [comment]
The whole config:
https://github.com/gHashTag/dotfiles

**Comment by maksimr** [comment]
@gHashTag Thanks,

Could you check version of *js-beautify*:
`cat vim-jsbeautify/plugin/lib/package.json | grep version`

**Comment by gHashTag** [comment]
` ~/.config/nvim/plugged/vim-jsbeautify/plugin/lib  ➦ ae68f00  cat package.json
{
  "name": "js-beautify",
  "version": "1.6.3",
  "description": "jsbeautifier.org for node",
  "main": "js/index.js",
  "bin": {
    "css-beautify": "./js/bin/css-beautify.js",
    "html-beautify": "./js/bin/html-beautify.js",
    "js-beautify": "./js/bin/js-beautify.js"
  },
  "directories": {
    "lib": "js/lib",
    "test": "js/test"
  },
  "scripts": {},
  "bugs": "https://github.com/beautify-web/js-beautify/issues",
  "homepage": "http://jsbeautifier.org/",
  "repository": {
    "type": "git",
    "url": "git://github.com/beautify-web/js-beautify.git"
  },
  "keywords": [
    "beautify",
    "beautifier",
    "code-quality"
  ],
  "author": "Einar Lielmanis <einar@jsbeautifier.org>",
  "contributors": [
    "Vital Batmanov <vital76@gmail.com>",
    "Chris J. Shull <chrisjshull@gmail.com>",
    "Gian Marco Gherardi <gianmarco.gherardi@gmail.com>",
    "Stan <stasson@orc.ru>",
    "Vittorio Gambaletta <VittGam@vittgam.net>",
    "Daniel Stockman <daniel.stockman@gmail.com>",
    "Harutyun Amirjanyan <amirjanyan@gmail.com>",
    "Nochum Sossonko <nsossonko@hotmail.com>",
    "Liam Newman <bitwiseman@gmail.com>"
  ],
  "license": "MIT",
  "dependencies": {
    "config-chain": "~1.1.5",
    "mkdirp": "~0.5.0",
    "nopt": "~3.0.1"
  },
  "devDependencies": {
    "jshint": "~2.9.1",
    "node-static": "~0.7.1",
    "mustache": "~2.2.1",
    "requirejs": "2.1.x",
    "benchmark": "2.1.0"
  }
}`

**Comment by maksimr** [comment]
Thanks,

I have the same version so then the problem isn't in js-beautify lib

**Comment by gHashTag** [comment]
In which direction to look for a mistake?

**Comment by maksimr** [comment]
You could set
`echo opts_Beautifier_arg`
before this line https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L414
and go to the file and run `call JsxBeautify()`
it will print options which we pass to the javascript. If they correct then a problem in the javascript part.

**Comment by zybtbu** [comment]
![image](https://user-images.githubusercontent.com/8773814/31434972-a02e8a62-ae43-11e7-86e4-ee17440fc6d9.png)

**Comment by maksimr** [comment]
@zybtbu Thanks

hm... It looks as correct JSON. 
we need to go deeper and debug javascript

**Comment by gHashTag** [comment]
Thanks. Now I am uses https://github.com/prettier/prettier
