### ISSUE TITLE
jsx beautify not working properly

### ISSUE THREAD

**Issue by strin** [maksimr/vim-jsbeautify#139]
I ran `call JsxBeautify()` on my `.jsx` file, and I got wrong indentation.

![image](https://user-images.githubusercontent.com/2183232/32120302-ee28784c-bb0c-11e7-9e40-61cb9aa29288.png)

**Comment by maksimr** [comment]
@strin try format your code here - http://jsbeautifier.org/
Looks like it's a problem of jsbeautifier

Thanks
