### ISSUE TITLE
when i use vim js format , is wrong

### ISSUE THREAD

**Issue by q2qiang** [maksimr/vim-jsbeautify#140]
![image](https://user-images.githubusercontent.com/20965435/34147551-0a0f431a-e4d9-11e7-9bfd-bc821260628a.png)
```
;.editorconfig

root = true

[**.js]
path=~/.vim/bundle/js-beautify/js/lib/beautify.js
bin=node
indent_style = space
indent_size = 4

[**.css]
path=~/.vim/bundle/js-beautify/js/lib/beautify-css.js
indent_style = space
indent_size = 4

[**.html]
indent_style = space
indent_size = 4
```

**Comment by maksimr** [comment]
@q2qiang  Did you define `g:config_Beautifier` in *.vimrc*?

**Comment by q2qiang** [comment]
yeah ,i can use it ,but it is wrong

![image](https://user-images.githubusercontent.com/20965435/34159493-6edac6ae-e504-11e7-8638-9920c8e1561c.png)

**Comment by maksimr** [comment]
@q2qiang `g:config_Beautifier` should contain **map**, not a string with a path. So in your case you should use `g:editorconfig_Beautifier`

> You can also configure a variable ```g: config_Beautifier```(g:config_Beautifier has type **dict**), but it is better to use the `.editorconfig` file.

> To assign a custom path for the `.editorconfig` file set the variable `g:editorconfig_Beautifier`.

https://github.com/maksimr/vim-jsbeautify/blob/master/README.md

Thanks!
