### ISSUE TITLE
Not proper formating with jinja template html

### ISSUE THREAD

**Issue by Migacz85** [maksimr/vim-jsbeautify#146]
I installed also js-beautify globally in console and is converting this file correctly. Not quite sure 
why I have this strange error ?

Code before: 
```HTML
{% extends 'main.html' %}
{%block content%}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <form class="form-signin"  method=POST action="{{ url_for('signup') }}">
                <h2 class="form-signin-heading">Register</h2>
                <br>
                <h4> If you want give a like <i class="red fas fa-heart text-danger"></i>  </h4>
                <h4> Add your own recipe  <i class="fas fa-plus text-warning"> </i></h4>
                <h4> Or edit existing ones <i class="fas fa-pen text-primary"> </i> </h4>
                <br>
                <h4>Please register here, I promise it will be quick <i class="fas fa-laugh-wink text-warning"> </i>    </h4>
                <br>
                <label for="inputUsername" class="sr-only">Username</label>
                <br>
                <input name="username" type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
                <br>
                <!-- <label for="inputEmail" class="sr-only">Email address</label>
                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                <br> -->
                
                <label for="inputPassword" class="sr-only">Password</label>
                <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                <br>
                <label for="inputPassword" class="sr-only">Password</label>
                <input name="password_check" type="password" id="inputPassword2" class="form-control" placeholder="Repeat password" required>
                <br>
                <button class="btn btn-lg btn-primary btn-block" type="submit">Register </button>
            </form>
            <br>
            {% if msg!='' %}
            <div class="alert alert-danger" role="alert">
                <strong>{{msg}}</strong> 
            </div>
            {%endif%}
        </div>
        
    </div>
</div> <!-- /container -->
{%endblock content%}
``` 

Code after:

```HTML	
{ % extends 'main.html' %
} { % block content %
} <
div class = "container" >
    <
    div class = "row justify-content-md-center" >
    <
    div class = "col-md-6" >
    <
    form class = "form-signin"
method = POST action = "{{ url_for('signup') }}" >
    <
    h2 class = "form-signin-heading" > Register < /h2> <
    br >
    <
    h4 > If you want give a like < i class = "red fas fa-heart text-danger" > < /i>  </h
4 >
    <
    h4 > Add your own recipe < i class = "fas fa-plus text-warning" > < /i></h
4 >
    <
    h4 > Or edit existing ones < i class = "fas fa-pen text-primary" > < /i> </h
4 >
    <
    br >
    <
    h4 > Please register here, I promise it will be quick < i class = "fas fa-laugh-wink text-warning" > < /i>    </h
4 >
    <
    br >
    <
    label
for = "inputUsername"
class = "sr-only" > Username < /label> <
    br >
    <
    input name = "username"
type = "text"
id = "inputUsername"
class = "form-control"
placeholder = "Username"
required autofocus >
    <
    br >
    <!-- <label for="inputEmail" class="sr-only">Email address</label>
    <
    input type = "email"
id = "inputEmail"
class = "form-control"
placeholder = "Email address"
required autofocus >
    <
    br > -->

    <
    label
for = "inputPassword"
class = "sr-only" > Password < /label> <
    input name = "password"
type = "password"
id = "inputPassword"
class = "form-control"
placeholder = "Password"
required >
    <
    br >
    <
    label
for = "inputPassword"
class = "sr-only" > Password < /label> <
    input name = "password_check"
type = "password"
id = "inputPassword2"
class = "form-control"
placeholder = "Repeat password"
required >
    <
    br >
    <
    button class = "btn btn-lg btn-primary btn-block"
type = "submit" > Register < /button> <
    /form> <
    br > { %
        if msg != '' %
    } <
    div class = "alert alert-danger"
role = "alert" >
    <
    strong > {
        {
            msg
        }
    } < /strong>  <
    /div> { % endif %
    } <
    /div>

    <
    /div> <
    /div> <!-- /container-- > { % endblock content %
    }
```

**Comment by Migacz85** [comment]
Ok I just figure it out that it was running JsBeautify() on .html file.
but I was using this code here. Should it run appropriate function to the 
file name after pressing ctrl+f  ?

Thanks 

'''
" Jsbeautify	
" /settings how code should be prettify is in .editorconfig
/* map <c-f> :call HtmlBeautify()<cr> */

" or
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
" for json
autocmd FileType json noremap <buffer> <c-f> :call JsonBeautify()<cr>
" for jsx
autocmd FileType jsx noremap <buffer> <c-f> :call JsxBeautify()<cr>
" for html
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
" for css or scss
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
" For visual sellection

'''

**Comment by maksimr** [comment]
@Migacz85 you should specify the appropriate handler for "html" file type in your vim config.
For example:

```vim
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
```
it'll call `HtmlBeautify` when you open a new buffer with filetype `html` and press `[ctrl-f]`

**Comment by Migacz85** [comment]
Hi 
That strange when I make like: 

`map <c-f> :call HtmlBeautify()<cr>`

And press ctrl+f on html file that is working like should. However this "dynamic"
shortcut association is not working. And when I have previous code uncommented and this one active:

```html
" or
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
" for json
autocmd FileType json noremap <buffer> <c-f> :call JsonBeautify()<cr>
" for jsx
autocmd FileType jsx noremap <buffer> <c-f> :call JsxBeautify()<cr>
" for html
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
" for css or scss
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
" For visual sellection
```


Nothing is happening, only cursor is going at the end of the file that's all.

**Comment by maksimr** [comment]
@Migacz85 Interesting,
Which version of vim you are using?

**Comment by Migacz85** [comment]
version 8.1.877

**Comment by maksimr** [comment]
@Migacz85 thanks,

You can try to run vim in verbose/debug mode and save the result to `vimlog` file 

- Run `vim -V20vimlog foo.html`
- Press `[Ctrl-f]`
- `:q!`

as result, you'll have `vimlog` file with debug information and there you can try to find
which "autocommand" applied  for current "html" file and does it really call `HtmlBeautify` function

![image](https://user-images.githubusercontent.com/616193/53290138-1acea480-37b1-11e9-8415-a3ed2770bb9e.png)
![image](https://user-images.githubusercontent.com/616193/53290144-2cb04780-37b1-11e9-812b-d3d4b2940049.png)

**Comment by Migacz85** [comment]
Omg, it created 20Megabytes files from it. Trying opening it resulted in frozening my vim. 
The only output I get was:
<www/4Project/templates/vimlog" [noeol] 38899L, 2189193C
I have quite a lot plugins this is maybe the reason. I will post my vimrc shortly

**Comment by Migacz85** [comment]
Here is my vimrc 

https://github.com/Migacz85/dotfiles/blob/master/.vimrc

**Comment by maksimr** [comment]
@Migacz85 your configuration of `vim-jsbeautify` works perfectly fine for me
Try to disable other plugins and check how it works

**Comment by Migacz85** [comment]
Just disabled everything and have some reasonable smaller file, still same results anyway.

https://gist.github.com/Migacz85/3d5887f878d6a2961aa04f9c7adef793

**Comment by Migacz85** [comment]
I turn of 95% of plugins. That is so strange. Now when I'm testing this, ctrl+f is working with normal .html files. But when Is commig to jinja  .html templates when I'm running ctrl+f that is not working. Is your ctrl+f is working fine with jinja templates? This is normal html but sometimes can iclude tags like this:
` {% extends 'main.html' %} {% block content%}`
On the other way, when call this directly is working.

**Comment by maksimr** [comment]
@Migacz85 yah, it works fine for me

![kapture 2019-02-24 at 0 52 45](https://user-images.githubusercontent.com/616193/53292091-9428c000-37ce-11e9-98b9-764f29bf8e06.gif)

I think the problem in configuration
```
autocmd FileType html nnoremap <buffer> <c-f> :call HtmlBeautify()<cr>
```

Because in vimlog I don't see that this command applied for open buffer.
Try to run command `set filetype` it should print `filetype` for current buffer

**Comment by Migacz85** [comment]
UFFF !!
Now that is working :-) It should land in Readme.md  

filetype is not` html` is` djangohtml` I cant belive that it took me so much time.

```html
" for django 
autocmd filetype htmldjango noremap <c-f> :call HtmlBeautify()<cr>
```

**Comment by maksimr** [comment]
@Migacz85 glad to hear it :)

No problem!
