### ISSUE TITLE
HTML format wrong !

### ISSUE THREAD

**Issue by yangxinyujy** [maksimr/vim-jsbeautify#152]
Everything is well, but for HTML is wrong!

![image](https://user-images.githubusercontent.com/32320149/75256251-21f21d80-581e-11ea-8e22-b290b3708f74.png)

![image](https://user-images.githubusercontent.com/32320149/75257899-a2198280-5820-11ea-9498-4292a9dffc44.png)

![image](https://user-images.githubusercontent.com/32320149/75257917-ab0a5400-5820-11ea-80c0-398aa524b249.png)

**Comment by maksimr** [comment]
@yangxinyujy you call the wrong function `JsBeautify`

![image](https://user-images.githubusercontent.com/616193/75266505-7d62e200-5803-11ea-9095-2c3adc280319.png)

but you should **call `HtmlBeautify `** for html
https://github.com/maksimr/vim-jsbeautify#usage
