### ISSUE TITLE
Tab Indentation

### ISSUE THREAD

**Issue by stanleygu** [maksimr/vim-jsbeautify#21]
There does not appear to be a way to set the indentation style to tabs using `.editorconfig`.

**Comment by luckydrq** [comment]
@maksimr exec `:echo b:config_Beautifier` in my vim is `{'jsx': {}, 'js': {}, 'json': {}, 'html': {}, 'css': {}}`, why is that? My `.editorconfig` locates at my home directory.

**Comment by luckydrq** [comment]
![image](https://cloud.githubusercontent.com/assets/1474688/11761133/fdbff75e-a0f0-11e5-8b63-e2137ab2a147.png)

**Comment by luckydrq** [comment]
Problem solved. 

Remove `~/.editorconfig` and modify `path/to/vim-jsbeautify/plugin/.editorconfig`, it works.

But i still have no idea why it fails with `~/.editorconfig` set up.

**Comment by maksimr** [comment]
@luckydrq looks very strange...

Do you have `g:config_Beautifier` or `g:editorconfig_Beautifier` defined?
Maybe problem in $HOME variable can you check in vim $HOME `:echo $HOME`

**Comment by luckydrq** [comment]
`:echo $HOME` outputs `/Users/xuezu` which is correct.

**Comment by luckydrq** [comment]
>Do you have g:config_Beautifier or g:editorconfig_Beautifier defined?

Sorry, i'm new to vim. How to check if the variable is defined?

PS: i'm using OSX10.10.5 and ide is macvim

**Comment by maksimr** [comment]
@luckydrq you can simple type `:echo g:editorconfig_Beautifier`

**Comment by maksimr** [comment]
@luckydrq you can check can we read file in root or not by command:

`:echo filereadable(expand('$HOME/.editorconfig'))` if it's print 1 then yes if 0 then no

**Comment by luckydrq** [comment]
@maksimr  

After execute the `echo g:xxx` command, i find out `g:editorconfig_Beautifier` is not defined. Is it normal?  

`:echo filereadable(expand('$HOME/.editorconfig'))` outputs `1` which is yes

**Comment by luckydrq** [comment]
Does the  `~/.editorconfig` takes prior to `vim-jsbeautify/plugin/.editorconfig`?

**Comment by maksimr** [comment]
> Does the ~/.editorconfig takes prior to vim-jsbeautify/plugin/.editorconfig?

[Yes](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L35)

>  find out g:editorconfig_Beautifier is not defined. Is it normal?

Yup.

But you can put it in your vimrc.

g:editorconfig_Beautifier = exapnd('$HOME/.editorconfig')
