### ISSUE TITLE
Support for `.jsbeautifyrc` files?

### ISSUE THREAD

**Issue by randallagordon** [maksimr/vim-jsbeautify#34]
I may be overlooking it, but is there currently a way to load options from a project specific `.jsbeautifyrc` config file?

**Comment by nivv** [comment]
I'm with @randallagordon, coming from a different environment I already have a `.jsbeautifyrc`. 

For example, some options are not respected. This is what my `html`-cfg looks like in my `.jsbeautifyrc`. How do I set the same options in my `.editorconfig`? For example, brace style seems to be ignored if I put it in my `.editorconfig`

```json
  "html": {
    "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "blade.php", "vue"],
    "brace_style": "collapse", // [collapse|expand|end-expand|none] Put braces on the same line as control statements (default), or put braces on own line (Allman / ANSI style), or just put end braces on own line, or attempt to keep them where they are
    "end_with_newline": true, // End output with newline
    "indent_char": " ", // Indentation character
    "indent_handlebars": false, // e.g. {{#foo}}, {{/foo}}
    "indent_inner_html": false, // Indent <head> and <body> sections
    "indent_scripts": "separate", // [keep|separate|normal]
    "indent_size": 4, // Indentation size
    "max_preserve_newlines": 1, // Maximum number of line breaks to be preserved in one chunk (0 disables)
    "preserve_newlines": true, // Whether existing line breaks before elements should be preserved (only works before elements, not inside tags or for text)
    "unformatted": ["a", "img", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big", "small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"], // List of tags that should not be reformatted
    "wrap_line_length": 0, // Lines should wrap at next opportunity after this number of characters (0 disables)
    "wrap_attributes": "auto",
    "wrap_attributes_indent_size": 4
  },
```

My .editorconfig

```ini
[**.html]
indent_style = space
indent_size = 4
max_char = 178
curly_bracket_next_line = false
;below is ignored
brace_style = collapse
```

**Comment by maksimr** [comment]
It's strange that brace_style is ignored.
@nivv you can install custom version of js-beautify because that the problem can be in version of js-beautify.

**Comment by nivv** [comment]
@maksimr thanks for answering! Although I had placed my `.editorconfig` in my project directory, and not in `~/.vim/.editorconfig` (when I read the docs I though you could have it in your project root dir as well). It works as expected now.

Only problem I have now is that inline `<script>`-tags has some issues, see below:

(Using HtmlBeautify)

```html
</template>
    <button class="btn btn-default pull-right" @click="showCreateUserModal"><i class="fa fa-plus"></i> Do stuff</button>
</template>

<script>
import alertMessage from '../partials/alertMessage.vue';
import parentOption from '../partials/pageParentOptions.vue';
//
export
default {
    props: ['pages', 'languages'],
    data: function() {
        return {
//....
</script>

```

I'd like the `export` statement to be on the same line. Like below:

```javascript
export default {
    props: ['pages', 'languages'],
```

**Comment by maksimr** [comment]
@nivv I think it is related to js-beautify not vim plugin. Could you run cli js-beautify for your html file and look on result?

**Comment by nivv** [comment]
@maksimr sure! 

```bash
$ js-beautify test.html --type=html
```
Output:

```html
<template>
    <button class="btn btn-default pull-right" @click="showCreateUserModal"><i class="fa fa-plus"></i> Lägg till sida</button>
</template>

<script>
    import alertMessage from '../partials/alertMessage.vue';
    import parentOption from '../partials/pageParentOptions.vue';
    //
    export default {
        props: ['pages', 'languages'],
    }
</script>
```

**Comment by maksimr** [comment]
@nivv what is version of js-beautify in vim-plugin you use and what is version of cli js-beautify?

**Comment by nivv** [comment]
@maksimr 

CLI
```bash
js-beautify --version
1.6.2
```

According to the readme inside  `~/.vim/bundle/vim-jsbeautify/plugin/lib/readme.md` it is `1.5.1`

**Comment by maksimr** [comment]
@nivv you can put path to custom js-beautify in .editorconfig https://github.com/maksimr/dotfiles/blob/master/export/_editorconfig.symlink#L7

**Comment by nivv** [comment]
@maksimr 

That kind of works, however, now it won't fix indentation for the html portion :/

**Comment by maksimr** [comment]
@nivv do you set path=...js-beautify/js/lib/beautify-html.js for html section?

**Comment by nivv** [comment]
@maksimr yup, weird huh? Can't you update the underlying `js-beautify` for this package though? It's a bit outdated, or maybe it will break other stuff?

**Comment by maksimr** [comment]
@nivv I have already tried update but it's [break](https://github.com/maksimr/vim-jsbeautify/pull/104) some tests

**Comment by nivv** [comment]
@maksimr yeah, seems to be same symptoms I'm getting. The config isn't read properly.
