### ISSUE TITLE
array elements on new line each

### ISSUE THREAD

**Issue by timsuchanek** [maksimr/vim-jsbeautify#41]
Nice, that you added options in the new version! But is there an option for js to put the content of arrays into a new line?
So instead of:

``` js
['a', 'b', 'c', 'd']
```

New line each:

``` js
[
    'a',
    'b',
    'c',
    'd'
]
```

Thanks!

**Comment by jackwootton** [comment]
Just in case anyone stumbles across this issue because they also want js-beautify to format array items one per line. I found that setting `wrap_line_length` to a very small number (i.e. 1) (but not 0) worked.
