### ISSUE TITLE
JsBeautify() is ignoring .editorconfig

### ISSUE THREAD

**Issue by nobleach** [maksimr/vim-jsbeautify#46]
I have tried my .editorconfig in both my ~/ dir and ~/.vim/ but it still is ignored. When I invoke :call JsBeautify() it uses 4 spaces instead of 2.

Here is my .editorconfig

root = true                                                                                                                                     

  [**.js]
  indent_style = space
  indent_size = 2 

  [**.css]
  indent_style = space
  indent_size = 2 

  [**.html]
  indent_style = space
  indent_size = 2 
  max_char = 78
  brace_style = expand

**Comment by XavM** [comment]
I can confirm that after removing leading spaces in the .editorconfig file, JsBeautify is not ignoring .editorconfig file any more 

Credits to @eds101

OSX 10.10.3 Yosemite with terminal.app

**Comment by maksimr** [comment]
@eds101 , @XavM thanks guys!
Can you provide small example of `editorconfig` with leading space I will try reproduce it on my linux

Thanks!

**Comment by trusktr** [comment]
> IMO - the default and first place to look in should be the .git parent directory if found (so it can be assigned per project).
> Then look in the CWD/.editorconfig and then $HOME whatever...

That's a very good idea @pgilad! <-- @maksimr

**Comment by TylerYang** [comment]
Hi, I found the same issue in my machine. (OSX Vim 7.4) And after I try to run the unit test with grunt, I got the errors below.

>> Testing beautify_all_test.js.......FFFFFFF
>> v8 - beautify JS
>> Message: should be formatted string.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.js" {} "plugin/lib/js/lib/beautify.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.js" {} "plugin/lib/js/lib/beautify.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '(["foo", "bar"]).each(function(i) {\n    return i;\n});'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:33:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> v8 - beautify JS with options
>> Message: should be formatted string with tab.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.js" "{\"indent_size\": 2, \"indent_char\": \"\t\"}" "plugin/lib/js/lib/beautify.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.js" "{\\"indent_size\\": 2, \\"indent_char\\": \\"\\t\\"}" "plugin/lib/js/lib/beautify.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '(["foo", "bar"]).each(function(i) {\n\t\treturn i;\n});'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:51:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> v8 - beautify HTML
>> Message: should be formatted string.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.html" {} "plugin/lib/js/lib/beautify-html.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.html" {} "plugin/lib/js/lib/beautify-html.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '<div>foo\n    <div></div>\n</div>'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:67:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> v8 - beautify HTML with options
>> Message: should be formatted string with tab.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.html" "{\"indent_size\": 2, \"indent_char\": \"\t\"}" "plugin/lib/js/lib/beautify-html.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.html" "{\\"indent_size\\": 2, \\"indent_char\\": \\"\\t\\"}" "plugin/lib/js/lib/beautify-html.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '<div>foo\n\t\t<div></div>\n</div>'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:85:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> v8 - HtmlBeautify() adding extra newline (issue 36)
>> Message: should save additional newline.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/issue_36.html" {} "plugin/lib/js/lib/beautify-html.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/issue_36.html" {} "plugin/lib/js/lib/beautify-html.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '<div>foo\n    <div></div>\n</div>\n\n'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:101:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> v8 - beautify CSS
>> Message: should be formatted string.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.css" {} "plugin/lib/js/lib/beautify-css.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.css" {} "plugin/lib/js/lib/beautify-css.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '.foo {\n    padding: 0;\n}'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:117:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>> v8 - beautify CSS with options
>> Message: should be formatted string with tab.
>> Actual:
>>   { [Error: Command failed: /bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.css" "{\"indent_size\": 2, \"indent_char\": \"\t\"}" "plugin/lib/js/lib/beautify-css.js"
>>   /bin/sh: v8: command not found
>>   ]
>>     killed: false,
>>     code: 127,
>>     signal: null,
>>     cmd: '/bin/sh -c v8 "plugin/beautify.js" --js_arguments "test/javascript/templates/test.css" "{\\"indent_size\\": 2, \\"indent_char\\": \\"\\t\\"}" "plugin/lib/js/lib/beautify-css.js"' }
>> Operator:
>>   ==
>> Expected:
>>   '.foo {\n\t\tpadding: 0;\n}'
>> at /Users/tyler/.vim/bundle/vim-jsbeautify/test/javascript/beautify_all_test.js:135:26
>> at ChildProcess.exithandler (child_process.js:210:5)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at maybeClose (internal/child_process.js:818:16)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>>Warning: 7/14 assertions failed (916ms) Use --force to continue.

Can somebody give me a hand? Thx.

**Comment by TylerYang** [comment]
After I comment out the v8 mixin in `beautify_all_test.js`, it passed javascript tests but stuck in the vim uni tests.(Wait for the Urchin task to finish more than 5 mins and nothing happened)  

And there is no such command 'v8' in my terminal. Can you tell me what is it used for ? Maybe I can try to debug in the js and vimscript.

**Comment by maksimr** [comment]
[v8] (http://code.google.com/p/v8/) is google js engine. In current version we support nodejs and v8 but maybe we should drop v8 and leave only nodejs.
vim tests use [urchin](http://www.urchin.sh) how test engine and  very fragile and I dont know work they or not on OS

Thanks

**Comment by sujith3g** [comment]
thanks @eds101,  got solved by removing leading white-spaces from `~/.editorconfig`.

**Comment by alex-shamshurin** [comment]
One year latter, the issue is still exists on OS X at least:
1. setting from all .editorconfig are ignored
2. for jsx files JSX settings are not applied (filletype is set)

**Comment by maksimr** [comment]
@alex-shamshurin could you show the content of `.editorconfig`?
I'm use macOs now and all work fine. 

Thanks

**Comment by alex-shamshurin** [comment]
```
;.editorconfig

root = true

[**.js?]
; path to optional external js beautifier, default is vim-jsbeautify/plugin/lib
;path=~/.vim/bundle/vim-jsbeautify/js/lib/beautify.js
; Javascript interpreter to be invoked by default 'node'
bin=node
indent_style = space
indent_size = 2

[*]

# Change these settings to your own preference
indent_style = space
indent_size = 2

# We recommend you to keep these unchanged
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

```

And what to do with incorrect function applied for jsx? Why jsxBeautify and jsBeautify functions yields same result?

Here is my vimrc
 
```
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
" for json
autocmd FileType json noremap <buffer> <c-f> :call JsonBeautify()<cr>
" for jsx
autocmd FileType jsx noremap <buffer> <c-f> :call JsxBeautify()<cr>
" for html
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
" for css or scss
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>"

autocmd FileType javascript vnoremap <buffer>  <c-f> :call RangeJsBeautify()<cr>
autocmd FileType json vnoremap <buffer> <c-f> :call RangeJsonBeautify()<cr>
autocmd FileType jsx vnoremap <buffer> <c-f> :call RangeJsxBeautify()<cr>
autocmd FileType html vnoremap <buffer> <c-f> :call RangeHtmlBeautify()<cr>
autocmd FileType css vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>
```

**Comment by maksimr** [comment]
@alex-shamshurin thanks,

If we say about global .editorconfig (not per project) then:

1. We try to find a config in these folders
```
1. '$HOME/.editorconfig', 
2. '$HOME/.vim/.editorconfig',
3. <BEAUTIFY_PLUGIN_FOLDER>.'/.editorconfig'
```

2. When we found config we [parse it](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L98-L161) (Be carefully **we use custom logic for parsing global
editor config!!!** We don't use editorconfig plugin for vim here)

Most important steps in parsing

2.a If we does not found section(js,jsx,html) in config we set it as empty object - https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L109-L113

2.b Section should look like [**.js] or [**.jsx] - https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L105

2.c Special comment should start with `;vim:` - https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L127

2.d We don't parse [*]


So in your editorconfig you have:

`[**.js?]` - violation 2.b
`;path=~/.vim/bundle/vim-jsbeautify/js/lib/beautify.js` -violation 2.c
`no set for jsx` - rule 2.a, we use empty object

As example of global editorconfig you could look at config https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/.editorconfig

Thanks

**Comment by alex-shamshurin** [comment]
Of course I need a local congig and it must take a precedence over global one. I found .editorconfig in plugin's folder.  I put this config https://github.com/maksimr/dotfiles/blob/master/export/_editorconfig.symlink into project's folder. And the plugin do not see it.

**Comment by maksimr** [comment]
@alex-shamshurin do you have installed https://github.com/editorconfig/editorconfig-vim?
Because we use a hook from this plugin inside a project folder.

**Comment by alex-shamshurin** [comment]
No. nobody told me ((( 
`Optional: editorconfig-vim` I thought it is not needed!

**Comment by alex-shamshurin** [comment]
I've just insalled it and what see I got - the same 4 spaces http://joxi.ru/p27808YIoZeXjA

**Comment by alex-shamshurin** [comment]
And in given [example config](https://github.com/maksimr/dotfiles/blob/master/export/_editorconfig.symlink)configs ;path is wrong,

**Comment by maksimr** [comment]
@alex-shamshurin try use [**.js] in your config, is it fix you problem?
What is wrong with [this](https://github.com/maksimr/dotfiles/blob/master/export/_editorconfig.symlink) path?

Thanks

**Comment by alex-shamshurin** [comment]
`;vim:path=~/.vim/bundle/js-beautify/js/lib/beautify.js` - wrong plugin name and location

**Comment by alex-shamshurin** [comment]
This is  my config 
```
root = true

[**.js]
;This section describe common
;javascript settings

;vim:bin=node
vim:max_char=130
indent_style = space
indent_size = 2

[**.jsx]
;vim:bin=node
vim:max_char=130
e4x = true
indent_style = space
indent_size = 2

[**.css]
vim:max_char=130
indent_style = space
indent_size = 2

[**.html]
indent_style = space
indent_size = 2
indent_inner_html=true
preserve_newlines=true
wrap-line-length = 0

[*]
indent_style = space
end_of_line = lf
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
max_line_length = 0
trim_trailing_whitespace = false
```
vimrc is above. It does not use  proper function for jsx formatting

**Comment by maksimr** [comment]
@alex-shamshurin I have added [test for your use case](https://github.com/maksimr/vim-jsbeautify/commit/3c74f5d6341a9d5ae0ddcbbae449d9189ccec1a8) and it works fine.
Please check settings in tests with yours.

Thanks
