### ISSUE TITLE
Add support jsx files

### ISSUE THREAD

**Issue by maksimr** [maksimr/vim-jsbeautify#55]

**Comment by FranckErnewein** [comment]
I just added the following line in my .editorconfig but it doesn't work
````
[**.jsx]
e4x = true
indent_style = space
indent_size = 2
````

Is there something else to do ?

**Comment by maksimr** [comment]
@FranckErnewein it's really strange

**Comment by jojoyuji** [comment]
same here. It's igoring .editorconfig [**.jsx]  :(

**Comment by maksimr** [comment]
@jojoyuji what function you are call for beautifying?
Maybe you use JsBeautify instead JsxBeautify
