### ISSUE TITLE
Doesn't format right on property getters and setters?

### ISSUE THREAD

**Issue by sinkingshriek** [maksimr/vim-jsbeautify#69]
Not sure if I'm the only one that's having this issue but when I do the following:-

    var obj = {
        get getValue() {
            console.log("Get something");
        },
        set setValue(value) {
            console.log("Setting something");
        }
    };

It gets formatted to the following:-

    var obj = {
       get getValue() {
               console.log("Get something");
           },
           set setValue(value) {
               console.log("Setting something");
           }
    };

Nothing special on the command, just did `:call JsBeautify()`. That's it.

**Comment by maksimr** [comment]
@sinkingshriek for me work with js-beautify@1.5.4

**Comment by sinkingshriek** [comment]
Closing. Seems to work now. :smile: Sorry took this long time.
