### ISSUE TITLE
Support for Custom web-components

### ISSUE THREAD

**Issue by mhartington** [maksimr/vim-jsbeautify#70]
Was wondering if there plans to support custom components and custom angular directives?
Since custom components are required to have a dash in them, things get messed up in the formatting. 

This repo here seems to have some syntax regex for css and html that support custom components.

https://github.com/azakus/vim-webcomponents

Would be great to see this added

**Comment by maksimr** [comment]
Close because issue of js-beautify project ;)

**Comment by mhartington** [comment]
My mistake, forgot about this :wink:
