### ISSUE TITLE
The node is not executable!

### ISSUE THREAD

**Issue by geekzgit** [maksimr/vim-jsbeautify#74]
![screenshot from 2015-01-04 17 24 01](https://cloud.githubusercontent.com/assets/5253183/5605445/7ffcb162-9436-11e4-975f-8ac55d43131b.png)
(function (global) { var $ = global.jQuery; if(!$){ return [ 'some',   'content']; } $('.class') .addClass('myclass') .removeClass('deleted'); }(this));

**Comment by maksimr** [comment]
@geekzgit by default plugin try run binary `node` or `nodejs`.
Do you have installed nodejs?

**Comment by geekzgit** [comment]
thx :)

**Comment by maksimr** [comment]
@geekzgit no problems

Problem is solved?

**Comment by geekzgit** [comment]
@maksimr yes,thank for your help :)

**Comment by mac10688** [comment]
I am having the same issue. I have iojs installed. I'm also using nvm https://github.com/creationix/nvm to manage my nodejs things. How do I fix this?

**Comment by mac10688** [comment]
I was finally able to resolve my issue with "nvm alias default iojs" and restarting vim.

**Comment by rolodato** [comment]
Stumbled upon this issue while Googling. Can confirm `nvm alias default iojs` worked for me as well.

**Comment by maksimr** [comment]
@mac10688, @rolodato you [can specify bin](https://github.com/maksimr/vim-jsbeautify#examples) in `.editorconfig`

```
bin=iojs
```
