### ISSUE TITLE
Support io.js

### ISSUE THREAD

**Issue by TimothyJin** [maksimr/vim-jsbeautify#76]
![image](https://cloud.githubusercontent.com/assets/1031636/5735779/849f6cf0-9c06-11e4-9950-da3c3ba5154c.png)

**Comment by maksimr** [comment]
@TimothyJin what engine you use? (node, v8)

**Comment by maksimr** [comment]
Related issue

https://github.com/maksimr/vim-jsbeautify/issues/30

**Comment by TimothyJin** [comment]
@maksimr io.js

**Comment by uzcc** [comment]
you may forgot to run `grunt build`

**Comment by maksimr** [comment]
@uzcc Thanks

fixed https://github.com/maksimr/vim-jsbeautify/commit/c33bff74dfb32cae19d85e3738368f251b00abc7
