### ISSUE TITLE
may I config the style by myself?

### ISSUE THREAD

**Issue by XadillaX** [maksimr/vim-jsbeautify#79]
My style is like:

```javascript
if(foo) {
    bar;
}
```

while the default style is:

```javascript
if (foo) {
    bar;
}
```

anyway to change the beautify style?

**Comment by maksimr** [comment]
@XadillaX yup, see [README](https://github.com/maksimr/vim-jsbeautify#settings).
You can use all settings from [js-beautify](https://github.com/beautify-web/js-beautify)

**Comment by XadillaX** [comment]
That's it. Thx.
