### ISSUE TITLE
insert_final_newline doesn't work

### ISSUE THREAD

**Issue by aharris88** [maksimr/vim-jsbeautify#81]
One of the options for the editor config it `insert_final_newline`, but even though I have mine set to true, it always removes the final newline.

    insert_final_newline: set to true ensure file ends with a newline when saving and false to ensure it doesn't.

**Comment by maksimr** [comment]
@aharris88 we use [js-beautify](https://github.com/beautify-web/js-beautify) for formatting, you should use options of `js-beautify`.
Try `end_with_newline` option

Thanks!

**Comment by aharris88** [comment]
Ok, but I thought it said that as of version 1.0, it also supported [editorconfig](http://editorconfig.org/), which has an option called `insert_final_newline`.

Is this not true? Do I have to use the options in js-beautify instead?

**Comment by maksimr** [comment]
Partially true.

You should define `js-beautify` options in `editorconfig` it allow setup formatting per project and simple reload formatting when navigate between project in same vim session.

We also [convert some](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L164-L183) `editorconfig` options to `js-beautify` options. We can convert `insert_final_newline` to `end_with_newline` if it has same effect.

Thanks

**Comment by aharris88** [comment]
Gotcha. That would be great if you could convert `insert_final_newline` to `end_with_newline` because my team uses editorconfig and I'm the only vim user.

I believe that both options are supposed to have the same effect.

**Comment by aharris88** [comment]
Fantastic! That works for me. Thanks for your quick response.
