### ISSUE TITLE
Do not overwrite C-f in example

### ISSUE THREAD

**Issue by inktrap** [maksimr/vim-jsbeautify#82]
Please choose another mapping to run jsbeautify. C-f [already has a meaning by default](http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-F). The F-keys (like F3) would be a better choice.

(You may test this by using an empty config and vim -u emptyconfig yourfile, then press C-f).

**Comment by maksimr** [comment]
@inktrap we don't set default mapping

**Comment by inktrap** [comment]
This is in your README under usage. There you overwrite <c-f>.

~~~
  ".vimrc

  map <c-f> :call JsBeautify()<cr>
  " or
  autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
  " for html
  autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
  " for css or scss
  autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>

**Comment by maksimr** [comment]
@inktrap this is **example** of usage. Plugin itself don't map <c-f> to `JsBeautify`

**Comment by inktrap** [comment]
Yes I know that it is an example (see the title). Most users will just copy the example.
Of course I and most of them use a different mapping and so should you.

**Comment by maksimr** [comment]
@inktrap sorry I can not understand the problem.
You can make PR with better example

Thanks

**Comment by souparno** [comment]
can you please tell me what script should i put in the vimrc if i want to call it from inside the vim like this
:JsBeautify

**Comment by inktrap** [comment]
Just change the keybinding like it says in the config.
I did the following, so <F4> is my toggle-key:

~~~
autocmd FileType javascript noremap <buffer>  <F4> :call JsBeautify()<cr>
~~~

**Comment by DGmip** [comment]
I used this default example and now I can't seem to map my <c-f> back to the original page down function. I need it!

**Comment by maksimr** [comment]
@DGmip could you provide your vimrc file

Thanks
