### ISSUE TITLE
Jsx support/documentation.

### ISSUE THREAD

**Issue by r-tock** [maksimr/vim-jsbeautify#83]
Based on the code I see partial support for jsx extension. However the configuration is not documented and jsx formatting breaks on simple cases for eg:

```javascript
  render: function() {
    if (!this.state.someMethod) {
      return (
        <div className="first">
          <Component1 />
        </div>
      );
    } else {
      return (
        <div className="second">
          <NavBar/>
          <Component2 />
        </div>
      );
    }
  },
```

**Comment by maksimr** [comment]
@r-tock put to .editorconfig

```
[**.jsx]
e4x = true
```

**Comment by r-tock** [comment]
That works!. The bug still stands, would be nice to update the README with jsx support.

**Comment by r-tock** [comment]
Looks like you did already! Sweet!
