### ISSUE TITLE
Single field objects should not expand

### ISSUE THREAD

**Issue by r-tock** [maksimr/vim-jsbeautify#84]
Its common in a react app to write a set field method

```javascript
_setFoo: function() { this.setState({foo: "bar"}); },
```

currently the beautifier expands that to and just scrolls.

```javascript 
_setFoo: function() { 
  this.setState({
    foo: "bar"
  }); 
},
```

Would be great to support a a folded version based on a flag option.

**Comment by maksimr** [comment]
@r-tock Thanks

Seems it's issue for [js-beautify](https://github.com/beautify-web/js-beautify).
My plugin wrap over *js-beautify*

**Comment by r-tock** [comment]
Thanks @maksimr, filed https://github.com/beautify-web/js-beautify/issues/674
