### ISSUE TITLE
not working anymore global.beautify() TypeError: Undefined is not a function

### ISSUE THREAD

**Issue by LifeSource** [maksimr/vim-jsbeautify#85]
Hi I'm not sure whats happened but for some reason my vim-jsbeautify no longer works, I've searched through previous issues but can't seem to figure out how to fix it as this seems to be slightly different.

Whenever I try <CTRL+F> to activate the beautifier in VIM for HTML/CSS/JS files I get the following. I've tried cleaning out my vim/bundle/ folder and restart again. Same error

[$HOME]/.vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1
l.beautify(content,options).replace(/\n$/g,""));return}print(global.beautify(c
                                                                    ^   
TypeError: undefined is not a function
    at [$HOME]/.vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1:1954
    at Object.<anonymous> ([$HOME].vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1:1982)
    at Object.<anonymous> ([$HOME].vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1:2011)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Environment details:
OS: Mac OSX Yosemite
Node version: v0.12.2
Vim: Terminal Vim 7.3
Shell: zsh

./vimrc configuration for js-beautify

" ------------------------------------------------------------------------
" JsBeautify Plugin settings
" ------------------------------------------------------------------------

" Insert Mode
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
"
" Visual Mode
autocmd FileType javascript vnoremap <buffer>  <c-f> :call RangeJsBeautify()<cr>
autocmd FileType html vnoremap <buffer> <c-f> :call RangeHtmlBeautify()<cr>
autocmd FileType css vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>

let s:rootDir = fnamemodify(expand("<sfile>"), ":h")
let g:jsbeautify_file = fnameescape(s:rootDir."/bundle/js-beautify/beautify.js")
let g:htmlbeautify_file = fnameescape(s:rootDir."/bundle/js-beautify/beautify-html.js")
let g:cssbeautify_file = fnameescape(s:rootDir."/bundle/js-beautify/beautify-css.js")

**Comment by maksimr** [comment]
@LifeSource Thanks!

What version of beautify.js you use?

**Comment by LifeSource** [comment]
I cloned it from the repo, not sure but in the README it says:

 vim-jsbeautify - v1.1.1 - 2012-12-27
