### ISSUE TITLE
What options can we configure? How?

### ISSUE THREAD

**Issue by trusktr** [maksimr/vim-jsbeautify#89]
I tried this editorconfig, as per the editorconfig docs, and it doesn't fully work:

```
[**.js]
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
max_line_length = 80
```

Lines aren't being wrapped when they are longer than 80 chars. It'd be super helpful if you'd list exactly which properties we can configure.

**Comment by trusktr** [comment]
Does it accept the options found in the README https://github.com/beautify-web/js-beautify? Which ones need to be `;vim` options?

**Comment by trusktr** [comment]
The example here shows

```
indent_style = space
```

But that option doesn't exist at https://github.com/beautify-web/js-beautify, instead they have

```
"indent_char": " ",
```

so it seems there's discrepancies. It'd be nice if these are documented!

**Comment by maksimr** [comment]
@trusktr you can use any `js-beautify` options, but [some](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L172-L184) editorconfig options was mapped to js-beautify options.

If you know js-beautify options which should be mapped to editorconfig options then will be nice if you create PR

Thanks!

**Comment by maksimr** [comment]
Feel free reopen
