### ISSUE TITLE
JsBeautify() outputs Powershell error under Windows

### ISSUE THREAD

**Issue by w1ld** [maksimr/vim-jsbeautify#92]
I'm using config similar to https://github.com/amix/vimrc and the shell is configured like this:

```vim
    set shell=powershell\ -ExecutionPolicy\ Unrestricted\ -NoProfile\ -NoLogo\ -NonInteractive
    set shellcmdflag=-command
    set shellpipe=|
    set shellredir=>
    set shellquote=\"
    set shellxquote=
```    

When I run `:call JsEautify()` it outputs this:

```
    At line:1 char:164
    + ...  C:/Users/USERNAME/AppData/Local/Temp/VIA6CF8.tmp {"indent_char": " ", "i ...
    +                                                                 ~
    Unexpected token ':' in expression or statement.
        + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : UnexpectedToken
   
```  
What can be the problem? Thanks for any help!

**Comment by maksimr** [comment]
@w1ld if remove this options all work as expected?

**Comment by w1ld** [comment]
@maksimr Yes, if all this is commented out it works. 

And when it is without `shellquote` and `shellxquote` it writes:

    Error detected while processing function JsBeautify..Beautifier:
    line 54:
    E484: Can't open file C:/..../Temp/..tmp

**Comment by ksmith97** [comment]
I ran into the issue with the temp files as well and resolved it by creating a folder with full control for everyone and adding `let $TMP="c:/tmp"` to my vimrc

**Comment by maksimr** [comment]
@ksmith97 Thanks!

**Comment by w1ld** [comment]
@ksmith97 , @maksimr 
I couldn't fix it.

'C:/temp' given all permissions. Settings:

	set shell=powershell\ -ExecutionPolicy\ Unrestricted\ -NoProfile\ -NoLogo\ -NonInteractive
	set shellcmdflag=-command
	set shellpipe=|
	set shellredir=>
	set shellquote=\'
	set shellxquote=

	let $TMP="C:/temp"

On `call JsBeautify()` it replaces the js obfuscated code with:

	At line:1 char:139
	+ ... ify.min.js --js_arguments C:/temp/VIA3F75.tmp {"indent_char": " ", "i ...
	+                                                                 ~
	Unexpected token ':' in expression or statement.
	    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
	    + FullyQualifiedErrorId : UnexpectedToken
 
If I comment out `shellquote` and `shellxquote` then the same error but only in the command window. It looks like JsBeautify can not be called via Powershell as it uses some of its syntax chars as "{", ":". So it is not fixed.

**Comment by ksmith97** [comment]
Sorry my comment was specifically about the issue with tmp files that you posted. I am running under a minty shell from cygwin.
