### ISSUE TITLE
Disable for a single line

### ISSUE THREAD

**Issue by JZL003** [maksimr/vim-jsbeautify#93]
Hi, 
For a certain line of code (` firstReponseURL = bcplResp.match(/<td width="1%" valign="top">[\r\n\s]*<a href="(\/Mobile\/Search\/Title\/[0-9\.]*)">/)[1]`) jsbeautify gets all wonky, is it possible to disable it for one line (so I can call control+c+f normally but it ignores that line to beautify). Ideally it would be something like a comment in the line above and below so as to tell jsbeautify to skip over the next line?

Edit: something like https://github.com/beautify-web/js-beautify/issues/384

**Comment by maksimr** [comment]
@JZL003 I think yes, because we use js-beautify. You can install latest version js-beautify and try add special comment.

Thanks! ;)

**Comment by maksimr** [comment]
Feel free reopen
