### ISSUE TITLE
ignoring editorconfig for auto wrap at 80 column

### ISSUE THREAD

**Issue by nettrino** [maksimr/vim-jsbeautify#94]
Hello, sorry if this is due to some misconfiguration of my vimrc, it seems that, although my .editorconfig
settings go through for the tabsize, no line wrap occurs at 80 columns. Also, running the tests I get "issue 18". 

Vim version 7.4.712, Mac OS X
Format options in .vimrc:
formatoptions=tcroqml

Output of echo b:config_Beautifier:

{'jsx': {'indent_char': ' ', 'max_line_length': '80', 'e4x': 'true', 'indent_style': 'space', 'indent
_size': '4', 'max_char': '78'}, 'js': {'indent_char': ' ', 'max_line_length': '78', 'indent_style': '
space', 'max_char': '78', 'indent_size': '4', 'bin': 'node', 'line_width': '78'}, 'json': {}, 'html':
 {'indent_char': ' ', 'brace_style': 'expand', 'max_line_length': '80', 'indent_style': 'space', 'ind
ent_size': '4', 'max_char': '78'}, 'css': {'indent_char': ' ', 'brace_style': 'expand', 'max_line_len
gth': '80', 'indent_style': 'space', 'indent_size': '4', 'max_char': '78'}}

Any ideas on why it does not automatically wrap lines?
Thanks!

**Comment by maksimr** [comment]
@nettrino try set

```
    wrap_line_length (default 250)            -  maximum amount of characters per line (0 = disable)
```
to editorconfig

**Comment by nettrino** [comment]
That seems to do the trick, thanks! It would be really cool to also add support for different formats of indenting if wrap is needed, for instance each argument in different line etc. In any case great work and thanks again!
