### ISSUE TITLE
Grab .editorconfig on a project basis

### ISSUE THREAD

**Issue by sinkingshriek** [maksimr/vim-jsbeautify#95]
This might possibly be a feature request or might already be how it's working but I think it would make sense to grab `.editorconfig` based on the project as this is what actually happens during collaboration. One project's `.editorconfig` file can be completely different from another so having one static `.editorconfig` in our `home` or `.vim/` directory seems to defeat the purpose of having `.editorconfig` in the first place.
Again, this might be how it's working right now but just for demonstration purpose let's say I'm working on a directory `/projects/work/workStuff` and that directory has `.editoconfig` file. When I call `vim-jsbeautify` it should first look in that directory for `.editorconfig`. If it can't find it then it goes up one directory..and up and so on until it can't go up anymore and it just looks at `home` or `.vim` directory and eventually uses the default `.editorconfig`.
I hope this makes sense and didn't make a fool of myself. 
Also, this might be the first beautifier plugin that actually leverages `.editorconfig` file or atleast from what I've tried in Atom and Sublime. Made me switch back to `vim` :grin:

**Comment by maksimr** [comment]
@sinkingshriek Thanks!

Plugin already should grab .editorconfig from project folder. Sometimes, when you change project .editorconfig, you should call function `:EditorConfigReload`

**Comment by sinkingshriek** [comment]
@maksimr Nice. I knew that this was an obvious implementation. Didn't know about the `:EditorConfigRelaod` however. Thank you!!

**Comment by maksimr** [comment]
@sinkingshriek no problem!
