### ISSUE TITLE
Форматирование переменных

### ISSUE THREAD

**Issue by lgick** [maksimr/vim-jsbeautify#97]
Здравствуйте!

Я привык писать переменные так:

```
var a = 3
  , b = 4;
```

```
var a
  , b;
```
(названия переменных на одном уровне и на новой строке)
Можно ли как-нибудь настроить опции плагина на такое форматирование?

Заметил, что после запуска JsBeautify() файл всегда приобретает вид измененного, хотя изменений никаких не происходит. Так и должно быть?

**Comment by maksimr** [comment]
@lgick Плагин использует [js-beautify](https://github.com/beautify-web/js-beautify) для форматирования. На странице [js-beautify](https://github.com/beautify-web/js-beautify) вы можете посмотреть все возможные конфигурационные параметры или задать вопрос в issues.

Я сходу не нашел набор настроек под то, что вы просите :(

> Заметил, что после запуска JsBeautify() файл всегда приобретает вид измененного, хотя изменений никаких не происходит. Так и должно быть?

Нет, это издержки реализации. Я еще не нашел решения как избавиться от этого нежелательного поведения. Про это есть задача https://github.com/maksimr/vim-jsbeautify/issues/61

Спасибо!
