### ISSUE TITLE
Add support for ES6 yield feature

### ISSUE THREAD

**Issue by xiulunlin** [maksimr/vim-jsbeautify#98]
Do not make `yield` a new line after calling jsbeautify.

    var result = yield async();
will become

    var result =
          yield async();

**Comment by maksimr** [comment]
@xiulunlin seems issue relate to [js-beautify](https://github.com/beautify-web/js-beautify). Because vim plugin simple wrapper around **js-beautify**.
Good idea create issue in [js-beautify](https://github.com/beautify-web/js-beautify/issues).

Thanks!

**Comment by xiulunlin** [comment]
@maksimr Thanks! Update `js-beautify` works.
