### ISSUE TITLE
Please use .editorconfig for default settings

### ISSUE THREAD

**Issue by alanerzhao** [maksimr/vim-jsbeautify#99]
When I use vim, always prompt me " Please use .editorconfig for default settings",
I have placed `editorconfig` files in the root directory

**Comment by maksimr** [comment]
@alanerzhao seems you have `g:jsbeautify` or `g:htmlbeautify` defined in your .vimrc

Thanks!

**Comment by maksimr** [comment]
You can use `g:config_Beautifier`  for setup from .vimrc

**Comment by alanerzhao** [comment]
thanks @maksimr 
![image](https://cloud.githubusercontent.com/assets/1327263/10036379/76e33918-61d9-11e5-946f-f33da67e57f7.png)
this is old other plugin。
